# Generated by Django 5.1.1 on 2024-09-14 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0002_entry"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topic",
            old_name="dete_added",
            new_name="date_added",
        ),
    ]
